export enum ActorActionType {
  ADD_ACTOR = "@@actor/ADD",
  REMOVE_ACTOR = "@@actor/REMOVE",
  UPDATE_ACTOR_ROLL = "@@actor/UPDATE_ROLL",
  HIGHLIGHT_NEXT_ACTOR = "@@actor/HIGHLIGHT_NEXT",
  BUMP_ACTOR_TO_LAST = "@@actor/BUMP_ACTOR_TO_LAST",
  UPDATE_ACTOR_LIST = "@@actor/UPDATE_ACTOR_LIST"
}

export enum GameActionType {
  INCREMENT_ROUND_COUNTER = "@@game/INCREMENT_ROUND_COUNTER",
  RESET_ROUND_COUNTER = "@@game/RESET_ROUND_COUNTER",
  TRY_ADD_ACTOR = "@@game/TRY_ADD_ACTOR",
  ROLL_FOR_INITIATIVE = "@@game/ROLL_FOR_INITIATIVE",
  FIGHT_THE_ENCOUNTER = "@@game/FIGHT_THE_ENCOUNTER",
  GATHER_YOUR_PARTY = "@@game/GATHER_YOUR_PARTY",
  START_AN_ENCOUNTER = "@@game/START_AN_ENCOUNTER"
}

export enum PartyActionType {
  ADD_PARTY_MEMBER = "@@party/ADD_MEMBER",
  REMOVE_PARTY_MEMBER = "@@party/REMOVE_MEMBER"
}
